version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lahman2016
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/lahman2016.sql:/docker-entrypoint-initdb.d/lahman2016.sql

  spark:
    image: bitnami/spark:latest
    container_name: spark
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"  # Spark UI
      - "7077:7077"  # Spark Master
    volumes:
      - ./notebooks:/opt/spark/work-dir

#  minio:
#    image: minio/minio:RELEASE.2025-03-12T18-04-18Z
#    container_name: minio
#    platform: linux/arm64  # This ensures the ARM64 version is used.
#    environment:
#      - MINIO_ROOT_USER=minioadmin
#      - MINIO_ROOT_PASSWORD=minioadmin
#    ports:
#      - "9000:9000"      # HTTP access
#      - "44443:44443"    # HTTPS access
#    volumes:
#      - minio_data:/data
#    command: server /data
#    restart: always

  etl:
    build: ./app
    container_name: etl-job
    depends_on:
      - mysql
      - spark
#      - minio
    volumes:
      - ./app:/app
      - ./output:/app/output
    environment:
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: password

volumes:
  mysql_data:
  minio_data:
